blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),

     path('blog/blog_detail/<int:blog_id>', views.blog_detail, name='blog_detail'),

    path('blog/pub_blog', views.pub_blog, name='pub_blog'),

    path('blog/comment/pub', views.pub_comment, name='pub_comment'),

    path('search', views.search, name='search')
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('blog.urls')),

    path('user_auth/',include("user_auth.urls"))
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'

urlpatterns = [
    path('login', views.user_login, name='login'),

    path('logout',views.user_logout, name='logout'),

    path('register', views.register, name='register'),

    path('email_captcha', views.send_captcha, name='email_captcha')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %} {% endblock  %}
</head>
<body>
<header class="p-3 text-bg-light mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/static" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <img src="{% static '/image/blog.png' %}" alt="" style="height: 40px">
        </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>
            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}">
                <input type="search" name="q" class="form-control " placeholder="搜索" aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'image/profile.png' %}" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li><a class="dropdown-item" href="{% url 'user_auth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'user_auth:login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'user_auth:register' %}" type="button" class="btn btn-warning">注册</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>

<main class="container bg-white p-3 rounded ">
    {% block main %} {% endblock %}
</main>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/default.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block title %}详细信息{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/profile.png' %}" alt="" class="rounded-5" height="30px" width="30px">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 h时i分 "}}发布</span>
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论（{{ blog.comments.all|length }}）</h3>
        <form action="{% url 'blog:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary"> 评论</button>
            </div>
        </form>
        <div class="mt-2">
            <ul class="list-group list-group-flush">
                {% for comment in blog.comments.all %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between .text-body-secondary">
                            <div class="user_info">
                                <img src="{% static 'image/profile.png' %}" alt="" class="rounded-5" height="40px"
                                     width="40px">
                                <span class="ms-2">{{ comment.author.username }}</span>
                            </div>
                            <div class="creat-time" style="line-height: 40px;">
                                {{ comment.pub_time|date:"Y年m月d日 h时i分 "}}
                            </div>
                        </div>
                        <div class="mt-3">{{ comment.content }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <script>
    hljs.highlightAll();
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}首页{% endblock %}

{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-4">
    {% for blog in blogs %}
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 100px">
                    <p class="card-text">{{ blog.content|striptags|truncatechars:200}}</p>
                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/profile.png' %}" alt="" class="rounded-5" height="30px" width="30px">
                        {{ blog.author.name }}
                    </div>
                    <div>发布时间：{{ blog.pub_time|date:"Y年m月d日 h时i分 "}}</div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}登录{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1 class="text-center">登录</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remeber" value="1" id="checkDefault">
                <label class="form-check-label" for="checkDefault">
                    记住我
                </label>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100" > 立即登录</button>
            </div>

        </form>
    </div>
{% endblock %}

templates/pub_blog.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="https://unpkg.com/@wangeditor/editor@latest/dist/css/style.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/pub_blog.css' %}">

    <script src="https://unpkg.com/@wangeditor/editor@latest/dist/index.js"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <script src="{% static 'jquery-3.7.1.min.js' %}"></script>

{% endblock %}
{% block title %}发布{% endblock %}

{% block main %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="POST">
        {% csrf_token %}
            <div class="mt-2">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mt-2">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                   {% for category in categories %}
                   	    <option value="{{ category.id }}">{{ category.name }}</option>
                   {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
        </form>
    </div>
    <div class="mt-3 text-end">
        <button class="btn btn-primary" id="submit-btn"> 发布</button>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}
{% block title %}注册{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1 class="text-center">注册</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="captcha" placeholder="验证码"
                           aria-label="Recipient’s username" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100" > 立即注册</button>
            </div>
        </form>
    </div>
{% endblock %}